# Generated by Django 3.1.5 on 2021-01-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210124_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Значение по-умолчанию', help_text='Дайте короткое название задаче', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Опишите суть задачи', verbose_name='Текст')),
                ('slug', models.SlugField(blank=True, help_text='Укажите адрес для страницы задачи. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес для страницы с задачей')),
            ],
        ),
    ]
