# Generated by Django 3.1.5 on 2021-01-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
