# Generated by Django 3.1.5 on 2021-01-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
