# Generated by Django 3.1.7 on 2021-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comments_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
