# Generated by Django 3.1.7 on 2021-02-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='content.Review'),
        ),
    ]
